# Generated by Django 4.1.7 on 2023-03-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_de_vehiculo', models.CharField(max_length=15)),
                ('modelo_anio_de_vehiculo', models.CharField(max_length=15)),
                ('motor', models.CharField(max_length=20)),
                ('descripcion_vehiculo', models.CharField(max_length=100)),
                ('datos_del_dueño', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Americano',
        ),
    ]
