# Generated by Django 4.1.7 on 2023-03-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarsApp', '0002_europeo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Japones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_de_vehiculo', models.CharField(max_length=15)),
                ('modelo_de_vehiculo', models.CharField(max_length=15)),
                ('motor', models.CharField(max_length=20)),
                ('descripcion_vehiculo', models.CharField(max_length=100)),
                ('nacionalidad_de_fabricante', models.CharField(max_length=15)),
            ],
        ),
    ]
