# Generated by Django 4.1.7 on 2023-03-20 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarsApp', '0003_vehiculos_valor_vehiuclo_usd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculos',
            old_name='descripcion_vehiculo',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='vehiculos',
            old_name='modelo_anio_de_vehiculo',
            new_name='modelo_de_vehiculo',
        ),
    ]
