# Generated by Django 4.1.7 on 2023-03-20 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarsApp', '0004_rename_descripcion_vehiculo_vehiculos_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculos',
            old_name='valor_vehiuclo_usd',
            new_name='valor_vehiculo_usd',
        ),
    ]
