# Generated by Django 4.1.7 on 2023-03-22 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CarsApp', '0005_rename_valor_vehiuclo_usd_vehiculos_valor_vehiculo_usd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculos',
            old_name='valor_vehiculo_usd',
            new_name='valor_vehiculo',
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='publicador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='publicados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='datos_del_dueño',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
