# Generated by Django 4.1.7 on 2023-03-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarsApp', '0006_rename_valor_vehiculo_usd_vehiculos_valor_vehiculo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos'),
        ),
    ]
