# Generated by Django 4.1.7 on 2023-03-27 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CarsApp', '0008_alter_vehiculos_descripcion_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='perfil',
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensaje', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
